# Generated by Django 4.2.2 on 2023-06-25 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'clinics',
                'verbose_name_plural': 'clinics',
            },
        ),
        migrations.CreateModel(
            name='Outpatient_schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.CharField(max_length=30)),
                ('workdays', models.CharField(choices=[('السبت', 'السبت'), ('الاحد', 'الاحد'), ('الاثنين', 'الاثنين'), ('الثلاثاء', 'الثلاثاء'), ('الأربعاء', 'الأربعاء'), ('الخميس', 'الخميس'), ('الجمعة', 'الجمعة')], max_length=10)),
                ('clinics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.clinics')),
            ],
            options={
                'verbose_name': 'Outpatient_schedule',
                'verbose_name_plural': 'Outpatient_schedules',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('phonenumber', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.CharField(max_length=500)),
                ('clinics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.clinics')),
            ],
            options={
                'verbose_name': 'booking',
                'verbose_name_plural': 'bookings',
            },
        ),
    ]
