# Generated by Django 4.2.2 on 2023-06-25 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outpatient_schedule',
            name='workdays',
            field=models.CharField(choices=[('السبت', 'السبت'), ('الاحد', 'الاحد'), ('الاثنين', 'الاثنين'), ('الثلاثاء', 'الثلاثاء'), ('الأربعاء', 'الأربعاء'), ('الخميس', 'الخميس'), ('الجمعة', 'الجمعة')], max_length=50),
        ),
    ]
