# Generated by Django 4.2.2 on 2023-06-25 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_outpatient_schedule_workdays'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='outpatient_schedule',
            name='workdays',
        ),
        migrations.AddField(
            model_name='outpatient_schedule',
            name='workdays',
            field=models.ManyToManyField(blank=True, related_name='work_days', to='booking.workday'),
        ),
    ]
