# Generated by Django 4.2.2 on 2023-06-26 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_clinics_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outpatient_schedule',
            name='clinics',
            field=models.ForeignKey(limit_choices_to={'available': True}, on_delete=django.db.models.deletion.CASCADE, to='booking.clinics'),
        ),
    ]
