# Generated by Django 4.2.2 on 2023-06-25 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='logo/')),
                ('phoennumbers', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=150)),
                ('fb_url', models.URLField()),
                ('tw_url', models.URLField()),
            ],
            options={
                'verbose_name': 'settings',
                'verbose_name_plural': 'settings',
            },
        ),
    ]
