# Generated by Django 4.2.2 on 2023-06-24 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inquiries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('phonenumber', models.IntegerField(verbose_name='phonenumber')),
                ('message', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'inquiries',
                'verbose_name_plural': 'inquiriss',
            },
        ),
    ]
